variables:
  # Azure service connection and environment details.
  AzureServiceConnection: [] # Set this in Azure DevOps if using pipelines
  AZURE_RM_SVC_CONNECTION: []
  EnvironmentToDeploy: dev

  SubscriptionId: f2539aa9-bbb8-4655-aa3b-8b123d573aa6
  ResourceGroupName: rg-indexer-sample
  ResourceGroupLocation: westeurope
  FunctionAppName: btindex
  KeyVaultName: [] # You don't have Key Vault
  AppInsightsName: btindex
  searchserviceendpoint: https://aibt94.search.windows.net/

  DockerImageRepository: []
  DockerFilePath: ./azure_functions/Dockerfile
  ContainerRegistryName: [] # You don't have ACR
  LandingAreaName: rgindexersample9c0d
  MLWorkspaceName: []


  CrawlerConfigurationStorageAccountUrl: https://rgindexersample9c0d.blob.core.windows.net/
  CrawlerConfigurationContainerName: mainconfig
  CrawlerConfigName: crawlers.yaml
  PriorityCrawlerConfigName: priority.yaml
  CrawlerLogLevel: INFO
  CrawlerRunSchedule: 0 */10 * * * *
  CrawlerPriorityRunSchedule: 0 */5 * * * *
  
  FuntionAppTimeOut: 02:30:00

